### ISSUE TITLE
flow-type

### ISSUE THREAD

**Issue by beleran** [dhorelik/crew-management#4]
Add static type checking, please.

**Comment by dhorelik** [comment]
will do later today along with the other issues. I haven't tried Flow yet. But maybe just a note that `propTypes` is used in the project already.

**Comment by dhorelik** [comment]
done

**Comment by beleran** [comment]
@dhorelik I can not find any `// @flow` annotations in the actual code.
How do you use it?

**Comment by dhorelik** [comment]
@beleran there is an option to enable it globally in `.flowconfig` - https://github.com/dhorelik/crew-management/blob/master/.flowconfig#L14

**Comment by beleran** [comment]
Looks good thank you.
