### ISSUE TITLE
Why do you have css and scss files in repo in the same time?

### ISSUE THREAD

**Issue by beleran** [dhorelik/crew-management#6]
https://github.com/dhorelik/crew-management/blob/5dd5b6df1a661ebbee37aae5f2e1d38151b0381e/src/components/Board/style.css#L1

**Comment by dhorelik** [comment]
missed that, they shoud've been in gitignore from the start - https://github.com/dhorelik/crew-management/commit/c13169aac036216d3abcc4506a4eb42e94c29ffd

**Comment by beleran** [comment]
Looks good. Thank you
